from .base import BaseCrawler
from .rss_fetcher import RSSFetcher
from .arxiv_fetcher import ArxivFetcher
from .github_fetcher import GitHubFetcher
from .semantic_scholar_fetcher import SemanticScholarFetcher
from .huggingface_fetcher import HuggingFaceFetcher
from .web_scraper import WebScraper
from .nju_scraper import NJUScraper
from .discovery import DiscoveryCrawler
